apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 8080 
      # port: Port den dieser Service exposed
      targetPort: 5000
      ## target Port: Port des Ziel-pods den dieser Service anspricht   
      #NodePort: 32410 
      #nodeport: Port auf dem dieser Service von außen erreichbar ist